### PR TITLE
Deleted the HTY icon theme after upgrading neoColor theme

### PR DESCRIPTION
**Pull request by aiamuzz**
@CareF ... i think we are ready to delete the HTY theme as discussed earlier ...

We now have

neoGrayS (Default)
neoGray
neoColor

I didn't want to directly delete from master just in case you didn't want it removed as yet ... If you are then you can go ahead and merge this PR.

### CODE REVIEW

**Comment by aiamuzz** [comment]
now that we've added the Night icons ... HTY will lack the same ... i guess we have to delete it

**Comment by CareF** [comment]
https://github.com/CareF/deepin-dock-plugin-neoweather/pull/5/commits/010912a04cc3e007a7463de5cda51222400cbc62
This commit won't do. 
5 days is maximum we can get from openweathermap for free account.

**Comment by aiamuzz** [comment]
> [010912a](https://github.com/CareF/deepin-dock-plugin-neoweather/commit/010912a04cc3e007a7463de5cda51222400cbc62)
> This commit won't do.
> 5-day is maximum we can get from openweathermap for free account.

oh ok ... i just checked the pricing ... its $ 40 / month for a paid account ... pretty expensive ... with no way of monetizing our project ... we need to stay happy with 5 days ... :)

And please do update me(preferably over chat) on the usage(your appID) data on your free account ... With $ 40 / a month ... Its important we keep an eye on it, especially after we release our plugin to stores across all distros that support DDE ... it will give us a fair amount of information on our plugin adoption/usage.

**Comment by CareF** [comment]
I don't think I can see any usage statistics... Until when we exceed the limit and openweathermap stops serving the appid. But let's not worry about it for now since I don't think it will be a problem to begin with.

**Comment by aiamuzz** [comment]
> [010912a](https://github.com/CareF/deepin-dock-plugin-neoweather/commit/010912a04cc3e007a7463de5cda51222400cbc62)
> This commit won't do.
> 5-day is maximum we can get from openweathermap for free account.

Is there anything i need take action over ... like delete this commit ?

**Comment by CareF** [comment]
> > [010912a](https://github.com/CareF/deepin-dock-plugin-neoweather/commit/010912a04cc3e007a7463de5cda51222400cbc62)
> > This commit won't do.
> > 5-day is maximum we can get from openweathermap for free account.
> 
> Is there anything i need take action over ... like delete this commit ?

delete this commit or change it back, then push to github.

**Pull request closed without merging**
